[book]
title = "Akuna"
authors = ["Akuna Team"]
language = "en"

[build]
build-dir = "target/book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/akunasoftware/akuna"
edit-url-template = "https://github.com/akunasoftware/akuna/edit/main/{path}"

[output.html.search]
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
