use std::{
    env, fs,
    path::{Path, PathBuf},
};

use crate::APP_NAME;

const ENV_XDG_CONFIG: &str = "XDG_CONFIG_HOME";
const ENV_XDG_DATA: &str = "XDG_DATA_HOME";

/// Application directory category to resolve.
pub enum AppDirType {
    /// User-editable configuration.
    Config,
    /// Persistent data generated by the application.
    Data,
}

/// Returns the first usable directory for the requested category.
///
/// Candidate order prefers a project-local dot directory when available,
/// then falls back to platform-specific locations.
pub fn get_app_dir(dir_type: AppDirType) -> PathBuf {
    let candidates = app_dir_candidates(dir_type);
    let path = candidates
        .iter()
        .find(|path| path.is_dir())
        .or_else(|| candidates.first())
        .expect(
            "application directory candidates always include local fallback",
        );

    let _ = fs::create_dir_all(path);

    path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
}

fn app_dir_candidates(dir_type: AppDirType) -> Vec<PathBuf> {
    match dir_type {
        AppDirType::Config => config_dir_candidates(),
        AppDirType::Data => data_dir_candidates(),
    }
}

fn config_dir_candidates() -> Vec<PathBuf> {
    let mut candidates = vec![local_config_dir()];

    if let Some(path) = env::var_os(ENV_XDG_CONFIG) {
        let xdg_path = PathBuf::from(path);
        candidates.push(xdg_path.join(APP_NAME));
        candidates.push(xdg_path.join(local_config_dir()));
    }

    if let Some(path) = dirs::config_dir() {
        candidates.push(path.join(APP_NAME));
        candidates.push(path.join(local_config_dir()));
    }

    dedupe_paths(candidates)
}

fn data_dir_candidates() -> Vec<PathBuf> {
    data_dir_candidates_for(&local_config_dir())
}

fn data_dir_candidates_for(local_dir: &Path) -> Vec<PathBuf> {
    let mut candidates = Vec::new();

    if local_dir.is_dir() {
        candidates.push(local_dir.join("data"));
    }

    if let Some(path) = env::var_os(ENV_XDG_DATA) {
        candidates.push(PathBuf::from(path).join(APP_NAME));
    }

    if let Some(path) = dirs::data_dir() {
        candidates.push(path.join(APP_NAME));
    }

    dedupe_paths(candidates)
}

fn local_config_dir() -> PathBuf {
    PathBuf::from(format!(".{APP_NAME}"))
}

fn dedupe_paths(paths: Vec<PathBuf>) -> Vec<PathBuf> {
    let mut unique = Vec::new();

    for path in paths {
        if unique.iter().any(|existing| existing == &path) {
            continue;
        }

        unique.push(path);
    }

    unique
}

#[cfg(test)]
mod tests {
    use std::fs;

    use anyhow::Result;

    use crate::dirs::AppDirType;

    use super::{
        app_dir_candidates, data_dir_candidates_for, local_config_dir,
    };

    #[test]
    fn conf_dirs_prefer_local_dot_dir() -> Result<()> {
        let candidates = app_dir_candidates(AppDirType::Config);

        assert_eq!(candidates.first(), Some(&local_config_dir()));
        Ok(())
    }

    #[test]
    fn data_dirs_prefer_local_dot_dir_when_present() -> Result<()> {
        let test_dir = tempfile::tempdir()?;
        let local_dir = test_dir.path().join(local_config_dir());

        fs::create_dir_all(&local_dir)?;
        let candidates = data_dir_candidates_for(&local_dir);

        assert_eq!(candidates.first(), Some(&local_dir.join("data")));
        Ok(())
    }
}
