[package]
name = "akuna-core"
authors.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
bench = false
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = []
testing = []
full = [
  "chunking",
  "chunking-tree-sitter", 
  "embedding", 
  "extraction", 
  "graph"
]

extraction = [
  "chunking", 
  "dep:burn-wgpu", 
  "dep:burn-magika", 
  "dep:pdf_oxide", 
  "dep:office_oxide",
  "dep:omniparse",
  "dep:rbook"
]
embedding = ["dep:burn-wgpu", "dep:burn-embed"]
graph = ["dep:akuna-core-macros", "dep:grafeo"]

chunking = ["dep:memchunk"]
chunking-tree-sitter = [
    "chunking",
    "dep:tree-sitter",
    "dep:tree-sitter-bash",
    "dep:tree-sitter-c",
    "dep:tree-sitter-c-sharp",
    "dep:tree-sitter-containerfile",
    "dep:tree-sitter-cpp",
    "dep:tree-sitter-css",
    "dep:tree-sitter-dart",
    "dep:tree-sitter-go",
    "dep:tree-sitter-graphql",
    "dep:tree-sitter-groovy",
    "dep:tree-sitter-hcl",
    "dep:tree-sitter-html",
    "dep:tree-sitter-java",
    "dep:tree-sitter-javascript",
    "dep:tree-sitter-json",
    "dep:tree-sitter-lua",
    "dep:tree-sitter-md",
    "dep:tree-sitter-php",
    "dep:tree-sitter-python",
    "dep:tree-sitter-ruby",
    "dep:tree-sitter-rust",
    "dep:tree-sitter-scala",
    "dep:tree-sitter-scss",
    "dep:tree-sitter-sequel",
    "dep:tree-sitter-svelte-next",
    "dep:tree-sitter-swift",
    "dep:tree-sitter-typescript",
    "dep:tree-sitter-vue-updated",
    "dep:tree-sitter-yaml",
]

[dependencies]
# core deps from workspace
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
dirs = { workspace = true }
walkdir = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
akuna-core-macros = { path = "../core-macros", optional = true }

# extraction features
pdf_oxide = { version = "0.3.30", optional = true, default-features = false }
office_oxide = { version = "0.1.2", optional = true, default-features = false }
omniparse = { version = "0.4.0", optional = true, default-features = false }
rbook = { version = "0.7.7", optional = true, default-features = false }

# ml features: (embedding, magika etc.)
burn-wgpu = { version = "0.21.0-pre.3", optional = true, default-features = false, features = ["std", "webgpu"] }
burn-magika = { git = "https://github.com/akunasoftware/burn-magika", optional = true }
burn-embed = { git = "https://github.com/akunasoftware/burn-embed", optional = true }

# graph: (storage, search etc.)
grafeo = { version = "0.5.42", optional = true, default-features = false, features = ["embedded", "hybrid-search", "rdf", "text-index", "vector-index"] }

# chunking features
memchunk = { version = "0.4.0", optional = true }
tree-sitter = { version = "0.26.9", optional = true }
tree-sitter-bash = { version = "0.25.1", optional = true }
tree-sitter-c = { version = "0.24.2", optional = true }
tree-sitter-c-sharp = { version = "0.23.5", optional = true }
tree-sitter-containerfile = { version = "0.8.0", optional = true }
tree-sitter-cpp = { version = "0.23.4", optional = true }
tree-sitter-css = { version = "0.25.0", optional = true }
tree-sitter-dart = { version = "0.2.0", optional = true }
tree-sitter-go = { version = "0.25.0", optional = true }
tree-sitter-graphql = { version = "0.1.0", optional = true }
tree-sitter-groovy = { version = "0.1.2", optional = true }
tree-sitter-hcl = { version = "1.1.0", optional = true }
tree-sitter-html = { version = "0.23.2", optional = true }
tree-sitter-java = { version = "0.23.5", optional = true }
tree-sitter-javascript = { version = "0.25.0", optional = true }
tree-sitter-json = { version = "0.24.8", optional = true }
tree-sitter-lua = { version = "0.5.0", optional = true }
tree-sitter-md = { version = "0.5.3", optional = true }
tree-sitter-php = { version = "0.24.2", optional = true }
tree-sitter-python = { version = "0.25.0", optional = true }
tree-sitter-ruby = { version = "0.23.1", optional = true }
tree-sitter-rust = { version = "0.24.2", optional = true }
tree-sitter-scala = { version = "0.26.0", optional = true }
tree-sitter-scss = { version = "1.0.0", optional = true }
tree-sitter-sequel = { version = "0.3.11", optional = true }
tree-sitter-svelte-next = { version = "0.1.1", optional = true }
tree-sitter-swift = { version = "0.7.2", optional = true }
tree-sitter-typescript = { version = "0.23.2", optional = true }
tree-sitter-vue-updated = { version = "0.1.0", optional = true }
tree-sitter-yaml = { version = "0.7.2", optional = true }


[dev-dependencies]
criterion = { version = "0.8.2", features = ["async_tokio"] }
tempfile = "3.27.0"

[[bench]]
name = "extraction"
harness = false
required-features = ["extraction", "testing"]

[[bench]]
name = "embedding"
harness = false
required-features = ["extraction", "embedding", "testing"]
