[package]
name = "akuna-core"
description = "A wholistic suite of tools required for knowledge work from extraction, embedding, graphs and more."
authors.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
bench = false
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = []
full = [
  "chunking",
  "detection",
  "embedding",
  "extraction",
  "reranking",
  "storage",
]

detection = ["dep:akuna-core-detection"]
extraction = ["dep:akuna-core-extraction", "akuna-core-extraction/tree-sitter"]
embedding = ["dep:akuna-core-embedding"]
reranking = ["dep:akuna-core-reranking"]
storage = ["dep:akuna-core-storage", "akuna-core-storage?/api"]

chunking = ["dep:akuna-core-chunking", "akuna-core-chunking/tree-sitter"]

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

akuna-core-chunking = { path = "../core-chunking", optional = true }
akuna-core-detection = { path = "../core-detection", optional = true }
akuna-core-embedding = { path = "../core-embedding", optional = true }
akuna-core-extraction = { path = "../core-extraction", optional = true }
akuna-core-reranking = { path = "../core-reranking", optional = true }
akuna-core-storage = { path = "../core-storage", optional = true }


[dev-dependencies]
tempfile = "3.27.0"
